[Fix] No longer reading empty lines as keys
lipkau/PsIni pull request #79
Opened 2024-10-08 23:47 UTC by HighPriest

Import-Ini was taking into consideration empty lines, as key-value pairs.  
This made exporting difficult, as the export function tried to write NoKey & NoValue into the output file.

This commit completely ignores empty lines, as they are of no interest when mapping a config file

2025-03-07 12:08 UTC, lipkau requested changes
Thank you for your PR!
I am sorry it took me so long to get to it.

I like the changes, but would appreciate you looking at my comment about the `.trim()`.

2025-03-07 12:08 UTC, lipkau commented on PSIni/Public/Import-Ini.ps1
> +                    $name = $_.Trim()
If memory serves, the `.trim()` was removed as a feature request to keep spaces.

How do you feel about using the `.trim()` only for the `if` condition?
```pwsh
if (-not [string]::IsNullOrWhiteSpace($name.Trim())) {
```

2025-03-11 14:40 UTC, HighPriest commented on PSIni/Public/Import-Ini.ps1
> +                    $name = $_.Trim()
Umm.  
I have looked through the code and these two lines are interesting.  
With `.Trim()` followed by `IsNullOrwhiteSpace()`, we are essentially checking only for `IsNull()`.  

Trying to recall what I tried to achieve with this `Trim()`. I believe I tried to use it as a "fix" for malformed inis, with random prefix/sufix whitespaces, not matching expected strings (e.g. missing some " WHATEVER ", because I was looking for "WHATEVER")  

With this included, all a user has to be bothered with, is 
```PowerShell
$hashMap.ContainsKey(iniData[$section][$name])
```
without this, user has to remember, to always include a `Trim()` in their code.
```PowerShell
$hashMap.ContainsKey(iniData[$section][$name].Trim())
```

2025-03-11 14:43 UTC, HighPriest commented on PSIni/Public/Import-Ini.ps1
> +                    $name = $_.Trim()
So, it is your call @lipkau  
Do you want to preserve the prefix / suffix whitespace for some users with special / very rare needs?  
Or do we want to be nice to users without these special, very rare needs & fix their malformed INIs for them?

2025-03-11 15:48 UTC, lipkau commented on PSIni/Public/Import-Ini.ps1
> +                    $name = $_.Trim()
I see this use case:
```
"    ooo`n  " > sample.ini
 $foo = Import-Ini sample.ini
 $foo["_"] 
```

I don't really see the benefit of stripping the whitespaces in such a key.
But we do it for the others too. I guess we should be consistent.

2025-03-11 22:38 UTC, HighPriest commented on PSIni/Public/Import-Ini.ps1
> +                    $name = $_.Trim()
Test added :)

2025-03-12 06:07 UTC, lipkau approved these changes
thank you!

2025-03-12 06:08 UTC, merged