[Fix] Improve performance by operating in-memory
lipkau/PSIni pull request #80
Opened 2024-10-08 23:54 UTC by HighPriest

This commit replaces all the Out-File operations,
with a list of strings to write at the end of programs (Export) execution.

All previous functionality, like "Encoding", "Appending", "Format", etc. are handled.

Improved execution time on a database of 1000files, from 284.7797556seconds to 58.9908463seconds (Almost 3x improvement)

2024-10-08 23:57 UTC, HighPriest commented
Have to be honest, I don't have the entire powershell development environment setup (addition of CONTRIBUTING.md would be useful), so I did not run the included tests.

Only tested the script for my workflow & the output is perfect. Including comments, adding things by hand, etc.

2025-03-07 12:03 UTC, lipkau requested changes
Thank you for your PR - it looks great!
The changes look solid and the tests passed on my machine.

I would appreciate you addressing the comments I left so that I can merge it.

2025-03-11 15:04 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
> +        #TODO: Make sure we are honoring "Append", "Encoding"
I am not removing any references to `$Encoding` in this PR.  
It seems, like the only place you have found `$Encoding` reference to be useful, is in `Remove-EmptyLines`  
https://github.com/lipkau/PsIni/blob/338d9a0a95324b50832db762c84f3db948854af2/PSIni/Public/Export-Ini.ps1#L167  
https://github.com/lipkau/PsIni/blob/338d9a0a95324b50832db762c84f3db948854af2/PSIni/Private/Remove-EmptyLines.ps1#L21-L22

2025-03-11 15:56 UTC, lipkau commented on PSIni/Public/Export-Ini.ps1
> +        #TODO: Make sure we are honoring "Append", "Encoding"
`-Encoding` was being passed to all `Out-File` commands, which you removed.
If you leave it in the splatting hash in line 134, the `Set-Content` in line 186 will also respect it.

2025-03-11 16:18 UTC, HighPriest commented on PSIni/Private/Out-Keys.ps1
> -            Append   = $Append
I see.  
fileParameters are no longer considered in OutKeys collection.  
This should resolve it 60b769c2953dbd7f286a5720e7eed3ceae6aac76

2025-03-11 16:32 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
> +        #TODO: Make sure we are honoring "Append", "Encoding"
Alright.  
I see that in the previous version, each line was written with `Out-File`, which has it's quirks  
& then, at the end of writing to the file, the file was read to memory & overwritten using `Set-Content` (in `Remove-EmptyLines.ps1`), which has a different set of quirks.

I am not aware of the initial idea behind using either in respective locations. Maybe you @lipkau remember why it was done this way?

Reference: https://stackoverflow.com/questions/10655788/powershell-set-content-and-out-file-what-is-the-difference

Now, there is only one read of **existingFile** contents (in target directory) & one write of new **fileContents**.

2025-03-11 16:34 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
> +        #TODO: Make sure we are honoring "Append", "Encoding"
Is this example correct?
https://github.com/lipkau/PsIni/blob/338d9a0a95324b50832db762c84f3db948854af2/PSIni/Public/Export-Ini.ps1#L18-L22

I see that `$PassThru` is used in only one place and not for what it is described in the .Example. Maybe I don't understand the `Get-Item` use
https://github.com/lipkau/PsIni/blob/338d9a0a95324b50832db762c84f3db948854af2/PSIni/Public/Export-Ini.ps1#L172-L176

2025-03-11 16:39 UTC, HighPriest commented on PSIni/Private/Save-WithCleanup.ps1
> +    Set-Content -Value $content -Path $Path -Encoding $Encoding -Force
@lipkau 
I am considering replacing `Set-Content` with `Out-File`, because:
- It doesn't block reading the target file
- It allows appending content to the file, without reading its contents to memory

on the other hand, if we are going to be swapping around Encoding & lineEnds, maybe it is better to read the entire targetFile into memory & replacing it in its entirety? What do you think @lipkau 

Reference about `Set-Content` & `Out-File`: https://stackoverflow.com/a/13544067

2025-03-11 18:24 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
> +            Write-Verbose "$($MyInvocation.MyCommand.Name):: Finished creating file: $Path"
@lipkau 
I am trying to find a way, to avoid reading the entire file to fix new line (carriage return) characters per platform.

Up to this point, the new line characters fix was done by reading the entire file & replacing its contents
```Powershell
    $content = (Get-Content -Path $Path -ErrorAction SilentlyContinue -Raw) -replace "(${lf})*$", "" -replace "(${lf}){3,}", ""
    Set-Content -Value $content -Path $Path -Encoding $Encoding -Force
```
in [Remove-EmptyLines.ps1](https://github.com/lipkau/PsIni/pull/80/files#diff-f1d7628bb63551b5cf295441b09f6818df47dfc219a78f928ba378fa4c3e2b52)


I am trying to understand if it is really necessary, or if it can't be done in some other way.  
Because the `Remove-EmptyLines.ps1` file was added with a "Implement Export-Ini" cf7f48fd7405070f71d8232bd0e49d5ee12f7557 commit. I am unable to determine, what exactly was the context of this ad-hoc fix.

### Thesis:
I believe it could be useful, when the .ini file is exchanged between Windows & Linux platforms.
But, to be honest, how often do you append from Linux to Windows files & not straight up overwrite the file in its entirety?

### Alternative solution:
If we are working with a pre-existing file, which moves between platforms & needs to be `-Appended`.  
Instead of writing to it, reading it all, fixing the newLines & writing to it again at the end of execution.  
I propose that if `-Append` is used, we read current file contents into memory, merge the data in memory & then write new contents into storage. This way, new lines issue is fixed by the `Out-File` function.

2025-03-11 18:29 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
> +            if ($Format -eq "pretty") { $fileContent += "" } # Separate Sections with whiteSpace
@lipkau 
If we don't do newLine fixing (mentioned in another comment), this has an interesting effect of creating an empty line at the end of files we write to.  
I am thinking, if in the end it is good or bad, or against some specification. Because this side effect has this nice property, that appending to a `-pretty` .ini file, we automatically get an empty line between old & new content.

This issue does not consider non `-pretty` .ini files, because they don't add these empty lines, so only one new line is added at the end of the file.

2025-03-13 21:50 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
> +            Write-Verbose "$($MyInvocation.MyCommand.Name):: Finished creating file: $Path"
So, I have slept on this task @lipkau 

## Conclusions
- `Remove-EmptyLines` handles:
    - removal of more than 1 empty line in the middle of the file 
    - removal of additional empty line at the end of the file
- The first issue does not concern us, because I have added removal of empty lines on import (in the other PR)
	- Output is always going to be only separated with one empty line, when it is needed
- The second issue only concerns "pretty" output, because we add an empty line at the end of sections

## Proposed actions
- Let the output have that lone, empty line at the end
    - This has the benefit of automatically separating Appends with an empty line
    - I don't know of a scenario, where empty line at the end of file, creates a problem

OR
- Fix the empty line, at the end of file, in memory. Before it is written to file. With this code:
```Powershell
# Remove empty line at the end of pretty output
if ($fileContent.Count -gt 0 && $Format -eq "pretty") {
    [array]::Resize([ref] $fileContent, $fileContent.Count - 1)
}
```

2025-03-13 21:55 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
> +            Write-Verbose "$($MyInvocation.MyCommand.Name):: Finished creating file: $Path"
Allowing the empty new line at the end of pretty .ini files, requires an update to the tests

2025-03-14 08:30 UTC, lipkau commented on PSIni/Private/Out-Key.ps1
> +        $outputLines = @()
This function no longer supports processing input via pipeline.

let's remove the `begin`, `processing` and `end` blocks to be consistent with other private functions.

2025-03-14 08:53 UTC, lipkau commented on PSIni/Public/Export-Ini.ps1
> +        }
consider this example:

```pwsh
"oi!" | Out-File test.txt -Append
cat test.txt
> oi!
"oi!" | Out-File test.txt -Append
cat test.txt
> oi!
> oi!
"oi!" | Out-File test.txt
cat test.txt
> oi!
```

I will really insist on removing this `if ($Append)` condition and passing the parameters to `Out-File`, as in:

```pwsh
Out-File -FilePath $Path -InputObject $fileContent -Append:$Append -Encoding $Encoding -Force:$Force
```

2025-03-14 08:55 UTC, lipkau commented on PSIni/Public/Export-Ini.ps1
consider this example:

```pwsh
"oi!" | Out-File test.txt -Append
cat test.txt
> oi!
"oi!" | Out-File test.txt -Append
cat test.txt
> oi!
> oi!
"oi!" | Out-File test.txt
cat test.txt
> oi!
```

I don't understand the need for checking the file existence and removing it when not appending. Passing the parameters to `Out-File` seems sufficient for me, as in:

```pwsh
Out-File -FilePath $Path -InputObject $fileContent -Append:$Append -Encoding $Encoding -Force:$Force
```

2025-03-14 08:58 UTC, lipkau commented on PSIni/Private/Remove-EmptyLine.ps1
> +    $content = (Get-Content -Path $Path -ErrorAction SilentlyContinue -Raw) -replace "(${lf})*$", "" -replace "(${lf}){3,}", ""
Why the `SilentlyContinue`?
Should we not fail if the file does not exist?

2025-03-14 09:00 UTC, lipkau commented on PSIni/Private/Save-WithCleanup.ps1
> +    Set-Content -Value $content -Path $Path -Encoding $Encoding -Force
reading to memory, processing and saving with `Out-File` seems appropriate to me.
I have opted for `Out-File` over `Set-Content` before.

I need to remember why I added the changing of line endings, tho 😕

2025-03-14 09:52 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
I agree it should be sufficient.  
I have not checked it, but one thing that comes to mind is metadata. I believe that overwriting the file is just going to change the `modified` parameter, while keeping `created` the same.

On the negative side of things, file removal could mess with access permissions.

There can be other scenarios when we might want or might not want to wipe metadata.

I think the file removal should be gone.

2025-03-14 10:11 UTC, HighPriest commented on PSIni/Private/Remove-EmptyLine.ps1
> +    $content = (Get-Content -Path $Path -ErrorAction SilentlyContinue -Raw) -replace "(${lf})*$", "" -replace "(${lf}){3,}", ""
I have moved the `silentlyContinue` from `Export-Ini` as a reminder of this function's (Remove-EmptyLines) existence.

In export it was used Because later on we are recreating/overwriting the file anyway.

Depending on how we want to handle new line cleaning, this function should be either deleted or marked as legacy code.

2025-03-14 10:12 UTC, lipkau commented on PSIni/Public/Export-Ini.ps1
## Thesis

There are plenty of pwsh native commands that write files. We should be in line with their behaviour.
(Which is for the `created` date not to be updated).
If we only use `Out-File` by passing the parameters, we will inevitably use the native behaviour.

## Example

### Out-File

```pwsh
function report($file) {cat $file; $item = Get-Item $file; $item.CreationTime; $item.LastWriteTime}
$file = "test.txt"
rm $file
Out-File -FilePath $file -InputObject "Hello, World!" -Append
report $file
sleep 5
Out-File -FilePath $file -InputObject "Hello, World!" -Append
report $file
sleep 5
Out-File -FilePath $file -InputObject "Hello, World!"
report $file
sleep 5
Out-File -FilePath $file -InputObject "Hello, World!" -Force
report $file
```

### Export-Csv

```pwsh
function report($file) {cat $file; $item = Get-Item $file; $item.CreationTime; $item.LastWriteTime}
$obj = [PSCustomObject]@{ Name = "Value" }
$file = "test.txt"
rm $file
Export-Csv -Path $file -InputObject $obj -NoTypeInformation -Append
report $file
sleep 5
Export-Csv -Path $file -InputObject $obj -NoTypeInformation -Append
report $file
sleep 5
Export-Csv -Path $file -InputObject $obj -NoTypeInformation
report $file
sleep 5
Export-Csv -Path $file -InputObject $obj -NoTypeInformation -Force
report $file
```

2025-03-18 19:18 UTC, HighPriest commented
Sorry for the delay.  
I forgot to push my things, but was still waiting for a review 🤪

2025-03-19 05:16 UTC, lipkau commented on Tests/Export-Ini.Unit.Tests.ps1
> +            $script:defaultFileContent = "[Category1]${lf}Key1 = Value1${lf};Key2 = Value2${lf}${lf}[Category2]${lf};Key1 = Value1${lf};Key2 = Value2${lf}${lf}"
I ran the tests and they are broken because of this changes in lines:
* 84
* 97
* 105
* 129
* 138
* 156

2025-03-19 05:20 UTC, lipkau commented on PSIni/Public/Export-Ini.ps1
You didn't make this change yet

2025-03-19 09:45 UTC, HighPriest commented on PSIni/Public/Export-Ini.ps1
Umm.  
`Remove-Item` should be gone in this commit
https://github.com/lipkau/PSIni/commit/f05f80df728d9922a18d3dfa19260f63045923e3

2025-03-19 09:45 UTC, HighPriest commented on Tests/Export-Ini.Unit.Tests.ps1
> +            $script:defaultFileContent = "[Category1]${lf}Key1 = Value1${lf};Key2 = Value2${lf}${lf}[Category2]${lf};Key1 = Value1${lf};Key2 = Value2${lf}${lf}"
Things would be easier if I knew how to run them. The bot doesn't execute them anymore for this PR :(

2025-03-19 13:44 UTC, merged